### ISSUE TITLE
quoted string arguments?

### ISSUE THREAD

**Issue by johnperry-math** [jhumphry/parse_args#2]
First, this is great. I've used it in several personal projects.

Is it possible to pass an argument that's a string with spaces? something like a _quoted_ string, as follows?
```
my_program --my_argument "string that has spaces"
```

**Comment by jhumphry** [comment]
Thanks, I'm glad people are finding it useful.

Handling quoted strings and treating them as a single command line argument is actually something the shell does before the program starts. It should work automatically without special treatment in your code. For example, using one of the example programs via the Bash shell you can set an example string option to something with spaces and punctuation:

```
[bin]$ ./simple_example --string "Hello, John Perry!"
Command name is: ./simple_example

Option bar was not set on the command line. Value: TRUE
Option string was set on the command line. Value: Hello, John Perry!
Option INFILE was not set on the command line. Value: INFILE
Option baz was not set on the command line. Value:  0
Option natural was not set on the command line. Value:  0
Option integer was not set on the command line. Value: -1
Option help was not set on the command line. Value: FALSE
Option long-only was not set on the command line. Value: FALSE
Option array was not set on the command line. Value: <Empty array>
Option short-only was not set on the command line. Value: FALSE
Option foo was not set on the command line. Value: FALSE

There were:  0 tail arguments.
```

Have I misunderstood your question? Or is there a problem with a particular shell?

**Comment by johnperry-math** [comment]
You're right! The difficulty I was having turns out to be an alire issue. When I run the built binary directly from the command line instead of using `alr run --args=...` everything works just fine.
